---
namespace: middleware_automation
name: jbcs
version: "1.1.2"
readme: README.md
authors:
  - Romain Pelisse <rpelisse@redhat.com>
  - Guido Grazioli <ggraziol@redhat.com>
description: Install and configure a JBoss Core Services server.
license_file: "LICENSE"
tags:
  - httpd
  - jbcs
  - rhel
  - jboss
  - infrastructure
  - server
  - runtimes
  - middleware
  - a4mw
dependencies:
  "middleware_automation.common": ">=1.1.0"
  "ansible.posix": ">=1.4.0"
repository: https://github.com/ansible-middleware/jbcs
documentation: https://ansible-middleware.github.io/jbcs
homepage: https://github.com/ansible-middleware/jbcs
issues: https://github.com/ansible-middleware/jbcs/issues
build_ignore:
  - .gitignore
  - .github
  - .ansible-lint
  - .yamllint
  - '*.tar.gz'
  - '*.zip'
  - molecule
  - changelogs
  - docs/_gh_include
  - docs/conf.py
  - docs/roles.rst.template
  - docs/requirements.yml
