---
- name: Check if mime.types exists
  ansible.builtin.stat:
    path: /etc/mime.types
  register: mime_types_file

- name: Create mime.types if missing
  become: true
  ansible.builtin.get_url:
    url: https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
    dest: /etc/mime.types
    mode: '0644'
  when: not mime_types_file.stat.exists
