---
- name: Post install HTTPD
  become: true
  ansible.builtin.template:
    src: templates/jbcs-httpd24-httpd.service.j2
    dest: "/usr/lib/systemd/system/{{ jbcs_service_name }}.service"
    owner: "{{ httpd.user.name }}"
    group: "{{ httpd.group.name }}"
    mode: 0640
  notify:
    - "Reload systemd"

- name: Ensure JBCS configuration is correct
  become: true
  notify:
    - "Restart JBCS"
  loop:
    - name: 00-base.conf
      dest: "{{ httpd.home }}/httpd/conf.modules.d"
    - name: httpd.conf
      dest:  "{{ httpd.home }}/httpd/conf"
  ansible.builtin.template:
    src: "templates/{{ item.name }}.j2"
    dest: "{{ item.dest }}/{{ item.name }}"
    owner: "{{ httpd.user.name }}"
    group: "{{ httpd.group.name }}"
    mode: 0640

- name: Ensure JBCS module configuration is correct
  become: true
  ansible.builtin.command: "mv {{ item }} {{ item }}.bak"
  args:
    removes: "{{ item }}"
    creates: "{{ item }}.bak"
    chdir: "{{ httpd.home }}/httpd/conf.d/"
  failed_when: false
  changed_when: false
  loop:
    - manual.conf
    - welcome.conf
