---
- name: Converge
  hosts: all
  vars:
    configure_firewalld: False
    offline_install: False
    bind_address: '*'
    omit_rhn_output: False
    rhn_username: "{{ lookup('env', 'PROD_JBOSSNETWORK_API_CLIENTID') }}"
    rhn_password: "{{ lookup('env', 'PROD_JBOSSNETWORK_API_SECRET') }}"
  roles:
    - middleware_automation.jbcs.jbcs
