---
name: CI
on:
  push:
    branches:
      - main
  pull_request_target:
  schedule:
    - cron: '0 6 * * *'

jobs:
  ci:
    uses: ansible-middleware/github-actions/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      fqcn: 'middleware_automation/jbcs'
      molecule_tests: >-
        [ "default" ]
